import { lazy, Suspense, useEffect, useMemo, useState } from 'react';
import { ArrowDownLeft, ArrowUpRight, BarChart3, ChevronDown, ChevronUp, CirclePlus, LayoutDashboard, List, Pencil, Plus, Search, Settings2, Trash2, WalletCards, X } from 'lucide-react';
import { addMonths, addYears, format, parseISO, subMonths, subYears } from 'date-fns';
import { es } from 'date-fns/locale';
import { categoryData, filterPeriod, money, summary, trendData } from './calculations';
import { bootstrapData, clearAllData, getAllData, loadPreferences, removeMovement, saveCategory, saveMovement, savePreferences } from './db';
import type { Category, Movement, MovementType, Preferences } from './types';
const TrendChart = lazy(() => import('./Charts').then(m=>({default:m.TrendChart})));
const ExpenseChart = lazy(() => import('./Charts').then(m=>({default:m.ExpenseChart})));
const WeeklyChart = lazy(() => import('./Charts').then(m=>({default:m.WeeklyChart})));

type Page = 'summary'|'movements'|'categories';
const today = format(new Date(),'yyyy-MM-dd');
const blank = (): Omit<Movement,'id'|'createdAt'|'updatedAt'> => ({type:'expense',amount:0,date:today,categoryId:'',concept:'',notes:''});

export default function App() {
  const [page,setPage]=useState<Page>('summary'); const [movements,setMovements]=useState<Movement[]>([]); const [categories,setCategories]=useState<Category[]>([]); const [prefs,setPrefs]=useState<Preferences>({periodMode:'month',selectedDate:today}); const [loading,setLoading]=useState(true); const [notice,setNotice]=useState(''); const [modal,setModal]=useState(false); const [editing,setEditing]=useState<Movement|null>(null);
  const reload=async()=>{const data=await getAllData();setMovements(data.movements);setCategories(data.categories.sort((a,b)=>a.order-b.order));};
  useEffect(()=>{(async()=>{await bootstrapData();await reload();const saved=await loadPreferences();if(saved)setPrefs(saved);setLoading(false)})()},[]);
  useEffect(()=>{if(!loading)savePreferences(prefs)},[prefs,loading]);
  const inPeriod=useMemo(()=>filterPeriod(movements,prefs.selectedDate,prefs.periodMode),[movements,prefs]); const totals=useMemo(()=>summary(inPeriod),[inPeriod]);
  const flash=(text:string)=>{setNotice(text);window.setTimeout(()=>setNotice(''),2500)};
  const openForm=(movement?:Movement)=>{setEditing(movement||null);setModal(true)};
  const onSaved=async(m:Movement)=>{await saveMovement(m);await reload();setModal(false);flash(editing?'Movimiento actualizado':'Movimiento añadido')};
  const deleteOne=async(m:Movement)=>{if(confirm(`¿Eliminar “${m.concept}”? Esta acción no se puede deshacer.`)){await removeMovement(m.id);await reload();flash('Movimiento eliminado')}};
  if(loading)return <div className="loading">Preparando tu espacio financiero…</div>;
  return <div className="app-shell">
    <aside><div className="brand"><span><WalletCards/></span><div><b>Cielo</b><small>Finanzas personales</small></div></div><nav>{([['summary',LayoutDashboard,'Resumen'],['movements',List,'Movimientos'],['categories',Settings2,'Categorías']] as const).map(([id,Icon,label])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}><Icon/>{label}</button>)}</nav><div className="aside-note"><span>Datos privados</span><p>Todo permanece en este navegador.</p></div></aside>
    <main><header><div><span className="eyebrow">Tu dinero, con claridad</span><h1>{page==='summary'?'Resumen financiero':page==='movements'?'Movimientos':'Categorías'}</h1></div>{page!=='categories'&&<button className="primary" onClick={()=>openForm()}><Plus/>Nuevo movimiento</button>}</header>
    {page==='summary'&&<Summary prefs={prefs} setPrefs={setPrefs} totals={totals} items={inPeriod} categories={categories}/>} 
    {page==='movements'&&<Movements items={movements} categories={categories} onEdit={openForm} onDelete={deleteOne}/>} 
    {page==='categories'&&<Categories categories={categories} reload={reload} onNotice={flash}/>} 
    </main><div className="mobile-nav">{([['summary',LayoutDashboard,'Resumen'],['movements',List,'Movimientos'],['categories',Settings2,'Categorías']] as const).map(([id,Icon,label])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}><Icon/><small>{label}</small></button>)}</div>
    {modal&&<MovementModal initial={editing} categories={categories} onClose={()=>setModal(false)} onSave={onSaved}/>}<div className="sr-live" aria-live="polite">{notice}</div>{notice&&<div className="toast">{notice}</div>}
  </div>;
}

function Summary({prefs,setPrefs,totals,items,categories}:{prefs:Preferences;setPrefs:(p:Preferences)=>void;totals:ReturnType<typeof summary>;items:Movement[];categories:Category[]}){
  const shift=(d:number)=>{const date=parseISO(prefs.selectedDate);setPrefs({...prefs,selectedDate:format(prefs.periodMode==='month'?(d>0?addMonths(date,1):subMonths(date,1)):(d>0?addYears(date,1):subYears(date,1)),'yyyy-MM-dd')})};
  const title=prefs.periodMode==='month'?format(parseISO(prefs.selectedDate),'MMMM yyyy',{locale:es}):format(parseISO(prefs.selectedDate),'yyyy'); const trend=trendData(items,prefs.selectedDate,prefs.periodMode); const cat=categoryData(items,categories);
  return <><section className="period-bar"><div className="segmented"><button className={prefs.periodMode==='month'?'active':''} onClick={()=>setPrefs({...prefs,periodMode:'month'})}>Mes</button><button className={prefs.periodMode==='year'?'active':''} onClick={()=>setPrefs({...prefs,periodMode:'year'})}>Año</button></div><div className="period-nav"><button onClick={()=>shift(-1)}>‹</button><strong>{title}</strong><button onClick={()=>shift(1)}>›</button></div></section>
  <section className="stats"><Stat label="Ingresos" value={totals.income} icon={<ArrowDownLeft/>} tone="green"/><Stat label="Gastos" value={totals.expenses} icon={<ArrowUpRight/>} tone="red"/><Stat label="Ahorro" value={totals.savings} icon={<WalletCards/>} tone={totals.savings>=0?'blue':'red'}/><Stat label="Tasa de ahorro" text={`${totals.rate.toFixed(1)} %`} icon={<BarChart3/>} tone="blue"/></section>
  {items.length===0?<Empty icon={<BarChart3/>} title="Todavía no hay datos en este periodo" text="Añade tu primer ingreso o gasto para empezar a ver la evolución de tus finanzas."/>:<Suspense fallback={<div className="chart-loading">Dibujando gráficos…</div>}><section className="charts"><article className="chart wide"><h2>Evolución del periodo</h2><p>Ingresos, gastos y ahorro</p><TrendChart data={trend}/></article><article className="chart"><h2>Gastos por categoría</h2><p>Dónde se va tu dinero</p><ExpenseChart data={cat}/></article><article className="chart"><h2>Comparación temporal</h2><p>{prefs.periodMode==='month'?'Vista semanal':'Vista mensual'}</p><WeeklyChart data={trend}/></article></section></Suspense>}</>;
}
function Stat({label,value,text,icon,tone}:{label:string;value?:number;text?:string;icon:React.ReactNode;tone:string}){return <article className={`stat ${tone}`}><div className="stat-icon">{icon}</div><span>{label}</span><strong>{text??money.format(value||0)}</strong></article>}
function Empty({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="empty"><span>{icon}</span><h2>{title}</h2><p>{text}</p></div>}

function Movements({items,categories,onEdit,onDelete}:{items:Movement[];categories:Category[];onEdit:(m:Movement)=>void;onDelete:(m:Movement)=>void}){
  const [query,setQuery]=useState('');const [type,setType]=useState<'all'|MovementType>('all'); const filtered=items.filter(m=>(type==='all'||m.type===type)&&(`${m.concept} ${m.notes||''}`.toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>b.date.localeCompare(a.date)); const category=(m:Movement)=>{const c=categories.find(c=>c.id===m.categoryId);return c?.subcategories.find(s=>s.id===m.subcategoryId)?.name||c?.name||'Sin categoría'};
  return <section><div className="filters"><label className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar por concepto o nota"/></label><select value={type} onChange={e=>setType(e.target.value as typeof type)}><option value="all">Todos los tipos</option><option value="income">Ingresos</option><option value="expense">Gastos</option></select></div>{filtered.length===0?<Empty icon={<List/>} title="No hay movimientos" text="Prueba con otros filtros o añade un movimiento nuevo."/>:<div className="table-wrap"><table><thead><tr><th>Fecha</th><th>Concepto</th><th>Categoría</th><th>Tipo</th><th className="amount">Importe</th><th><span className="sr-only">Acciones</span></th></tr></thead><tbody>{filtered.map(m=><tr key={m.id}><td>{format(parseISO(m.date),'dd MMM yyyy',{locale:es})}</td><td><b>{m.concept}</b>{m.notes&&<small>{m.notes}</small>}</td><td><span className="tag">{category(m)}</span></td><td>{m.type==='income'?'Ingreso':'Gasto'}</td><td className={`amount ${m.type}`}>{m.type==='expense'?'-':'+'}{money.format(m.amount)}</td><td className="actions"><button aria-label={`Editar ${m.concept}`} onClick={()=>onEdit(m)}><Pencil/></button><button aria-label={`Eliminar ${m.concept}`} onClick={()=>onDelete(m)}><Trash2/></button></td></tr>)}</tbody></table></div>}</section>;
}

function MovementModal({initial,categories,onClose,onSave}:{initial:Movement|null;categories:Category[];onClose:()=>void;onSave:(m:Movement)=>void}){
  const [form,setForm]=useState(()=>initial?{...initial}:{...blank(),categoryId:categories.find(c=>c.type==='expense'&&!c.archived)?.id||''}); const [error,setError]=useState(''); const active=categories.filter(c=>c.type===form.type&&(!c.archived||c.id===form.categoryId)).sort((a,b)=>a.order-b.order); const cat=active.find(c=>c.id===form.categoryId); const update=(p:Partial<typeof form>)=>setForm(current=>({...current,...p}));
  const submit=(e:React.FormEvent)=>{e.preventDefault();if(!form.concept.trim()){setError('Escribe un concepto.');return}if(!Number.isFinite(Number(form.amount))||Number(form.amount)<=0){setError('El importe debe ser mayor que cero.');return}if(!form.date||!form.categoryId){setError('Completa la fecha y la categoría.');return}const now=new Date().toISOString();onSave({...form,amount:Number(form.amount),concept:form.concept.trim(),id:initial?.id||crypto.randomUUID(),createdAt:initial?.createdAt||now,updatedAt:now})};
  const chooseType=(type:MovementType)=>update({type,categoryId:categories.find(c=>c.type===type&&!c.archived)?.id||'',subcategoryId:''});
  return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><div className="modal-head"><div><span className="eyebrow">Registro</span><h2 id="modal-title">{initial?'Editar movimiento':'Nuevo movimiento'}</h2></div><button aria-label="Cerrar" onClick={onClose}><X/></button></div><form onSubmit={submit}><div className="type-picker"><button type="button" className={form.type==='expense'?'active expense':''} onClick={()=>chooseType('expense')}>Gasto</button><button type="button" className={form.type==='income'?'active income':''} onClick={()=>chooseType('income')}>Ingreso</button></div><label>Concepto<input autoFocus value={form.concept} onChange={e=>update({concept:e.target.value})} placeholder="Ej. Compra semanal"/></label><div className="form-grid"><label>Importe (€)<input type="number" min="0.01" step="0.01" value={form.amount||''} onChange={e=>update({amount:Number(e.target.value)})} placeholder="0,00"/></label><label>Fecha<input type="date" value={form.date} onChange={e=>update({date:e.target.value})}/></label><label>Categoría<select value={form.categoryId} onChange={e=>update({categoryId:e.target.value,subcategoryId:''})}>{active.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Subcategoría<select value={form.subcategoryId||''} onChange={e=>update({subcategoryId:e.target.value})}><option value="">Sin subcategoría</option>{cat?.subcategories.filter(s=>!s.archived||s.id===form.subcategoryId).sort((a,b)=>a.order-b.order).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label></div><label>Notas <span>(opcional)</span><textarea value={form.notes||''} onChange={e=>update({notes:e.target.value})} placeholder="Añade algún detalle"/></label>{error&&<p className="form-error" role="alert">{error}</p>}<div className="form-actions"><button type="button" className="secondary" onClick={onClose}>Cancelar</button><button className="primary">{initial?'Guardar cambios':'Añadir movimiento'}</button></div></form></div></div>;
}

function Categories({categories,reload,onNotice}:{categories:Category[];reload:()=>Promise<void>;onNotice:(s:string)=>void}){
 const [open,setOpen]=useState<string[]>(categories.map(c=>c.id)); const toggle=(id:string)=>setOpen(o=>o.includes(id)?o.filter(x=>x!==id):[...o,id]); const editName=async(c:Category,subId?:string)=>{const old=subId?c.subcategories.find(s=>s.id===subId)?.name:c.name;const name=prompt('Nuevo nombre',old);if(!name?.trim())return;const next=subId?{...c,subcategories:c.subcategories.map(s=>s.id===subId?{...s,name:name.trim()}:s)}:{...c,name:name.trim()};await saveCategory(next);await reload();onNotice('Categoría actualizada')}; const archive=async(c:Category,subId?:string)=>{const next=subId?{...c,subcategories:c.subcategories.map(s=>s.id===subId?{...s,archived:!s.archived}:s)}:{...c,archived:!c.archived};await saveCategory(next);await reload()}; const move=async(c:Category,d:number)=>{await saveCategory({...c,order:Math.max(0,c.order+d)});await reload()}; const add=async(type:MovementType)=>{const name=prompt('Nombre de la nueva categoría');if(!name?.trim())return;await saveCategory({id:crypto.randomUUID(),name:name.trim(),type,order:categories.filter(c=>c.type===type).length,archived:false,subcategories:[]});await reload();onNotice('Categoría creada')}; const addSub=async(c:Category)=>{const name=prompt('Nombre de la subcategoría');if(!name?.trim())return;await saveCategory({...c,subcategories:[...c.subcategories,{id:crypto.randomUUID(),name:name.trim(),archived:false,order:c.subcategories.length}]});await reload()};
 const wipe=async()=>{if(!confirm('Se borrarán todos tus movimientos y cambios de categorías. ¿Continuar?'))return;if(!confirm('Esta acción es irreversible. ¿Borrar definitivamente todos los datos?'))return;await clearAllData();await reload();onNotice('Todos los datos se han borrado')};
 return <><div className="category-toolbar"><p>Personaliza la estructura sin perder el historial asociado.</p><div><button className="secondary" onClick={()=>add('income')}><Plus/>Categoría de ingreso</button><button className="primary" onClick={()=>add('expense')}><Plus/>Categoría de gasto</button></div></div><section className="category-columns">{(['income','expense'] as const).map(type=><div key={type}><h2>{type==='income'?'Ingresos':'Gastos'}</h2>{categories.filter(c=>c.type===type).sort((a,b)=>a.order-b.order).map(c=><article className={`category-card ${c.archived?'archived':''}`} key={c.id}><div className="category-head"><button className="expand" onClick={()=>toggle(c.id)}>{open.includes(c.id)?<ChevronUp/>:<ChevronDown/>}</button><strong>{c.name}</strong>{c.archived&&<span className="tag">Archivada</span>}<div className="category-actions"><button onClick={()=>move(c,-1)} aria-label="Subir"><ChevronUp/></button><button onClick={()=>move(c,1)} aria-label="Bajar"><ChevronDown/></button><button onClick={()=>editName(c)} aria-label="Renombrar"><Pencil/></button><button onClick={()=>archive(c)}>{c.archived?'Activar':'Archivar'}</button></div></div>{open.includes(c.id)&&<div className="sub-list">{c.subcategories.sort((a,b)=>a.order-b.order).map(s=><div className={s.archived?'archived':''} key={s.id}><span>{s.name}</span>{s.archived&&<small>Archivada</small>}<button onClick={()=>editName(c,s.id)} aria-label={`Renombrar ${s.name}`}><Pencil/></button><button onClick={()=>archive(c,s.id)}>{s.archived?'Activar':'Archivar'}</button></div>)}<button className="add-sub" onClick={()=>addSub(c)}><CirclePlus/>Añadir subcategoría</button></div>}</article>)}</div>)}</section><section className="danger-zone"><div><h2>Borrar todos los datos</h2><p>Restablece movimientos, preferencias y categorías originales.</p></div><button onClick={wipe}><Trash2/>Borrar todo</button></section></>;
}
